import { PropsWithChildren, ReactNode } from 'react'
import { Button, Image, Input, Text, View } from '@tarojs/components'
import { navigationAdapter } from '@/platform'
import type { Listing, ListingStatus } from '@/domain/types'

export function BrandHeader({ title = 'BITerStore', back = false, action }: { title?: string; back?: boolean; action?: ReactNode }) { return <View className='brand-header'>{back ? <Button className='icon-button' onClick={() => navigationAdapter.back()}>‹</Button> : <View className='brand-mark'>B</View>}<View className='brand-title'><Text>{title}</Text><Text className='brand-subtitle'>书页轻翻 · 好物续航</Text></View><View className='header-action'>{action}</View></View> }
const h5Tabs = [['home', '首页'], ['search', '搜索'], ['publish', '发布'], ['messages', '消息'], ['profile', '我的']] as const
function H5Navigation() {
  if (process.env.TARO_ENV !== 'h5') return null
  return <View className='h5-navigation'>{h5Tabs.map(([route, label]) => <Button key={route} id={`e2e-nav-${route}`} onClick={() => navigationAdapter.switchTab(`/pages/${route}/index`)}><Text className='nav-dot'>{label.slice(0, 1)}</Text><Text>{label}</Text></Button>)}</View>
}
export function AppShell({ children, title, back, className = '' }: PropsWithChildren<{ title?: string; back?: boolean; className?: string }>) { return <View className={`app-shell ${className}`}><BrandHeader title={title} back={back} /><View className='page-scroll'>{children}</View><H5Navigation /></View> }
export function Tobby({ mood = 'hello', caption }: { mood?: 'hello' | 'search' | 'heart' | 'question' | 'sad' | 'maintenance' | 'cheer'; caption?: string }) { return <View className='tobby'><Image mode='aspectFit' src={`/assets/tobby-${mood}.webp`} />{caption && <Text>{caption}</Text>}</View> }
export function StatusTag({ status }: { status: ListingStatus }) { const labels: Record<ListingStatus, string> = { available: '可交易', sold: '已售出', offline: '已下架', draft: '草稿' }; return <Text className={`status-tag ${status}`}>{labels[status]}</Text> }
export function ListingCard({ listing, onTap }: { listing: Listing; onTap?: () => void }) { return <Button id={`e2e-listing-${listing.id}`} className='listing-card' onClick={onTap}><View className={`book-cover ${listing.tone}`}><Text>{listing.title.slice(0, 8)}</Text></View><View className='listing-copy'><View className='listing-heading'><Text className='listing-title'>{listing.title}</Text><StatusTag status={listing.status} /></View><Text className='listing-meta'>{listing.author} · {listing.condition}</Text><Text className='listing-meta'>{listing.campus}校区 · {listing.course}</Text><View className='price-row'><Text className='price'>¥{listing.price}</Text><Text className='original'>¥{listing.originalPrice}</Text></View></View></Button> }
export function FormField({ label, value, placeholder, onInput, type = 'text', id }: { label: string; value: string; placeholder?: string; onInput: (value: string) => void; type?: 'text' | 'number'; id?: string }) { return <View className='form-field'><Text>{label}</Text><Input id={id} type={type} value={value} placeholder={placeholder} onInput={(event) => onInput(event.detail.value)} /></View> }
export function Toast({ children }: PropsWithChildren) { return <View className='inline-toast'>{children}</View> }
export function Modal({ open, title, children, onClose }: PropsWithChildren<{ open: boolean; title: string; onClose: () => void }>) { if (!open) return null; return <View className='modal-mask' onClick={onClose}><View className='modal-card' onClick={(event) => event.stopPropagation()}><Text className='section-title'>{title}</Text>{children}<Button id='e2e-modal-close' onClick={onClose}>知道了</Button></View></View> }
export function FilterDrawer({ open, children, onClose }: PropsWithChildren<{ open: boolean; onClose: () => void }>) { if (!open) return null; return <View className='drawer-mask' onClick={onClose}><View className='filter-drawer' onClick={(event) => event.stopPropagation()}>{children}</View></View> }
