import fs from 'node:fs'
import path from 'node:path'
import automator from 'miniprogram-automator'
import { assertLocalPaths, automationPort, cliPath, projectPath, root, wsEndpoint } from './weapp-env.mjs'

const mode = process.argv.includes('--connect') ? 'connect' : 'launch'
const artifactRoot = path.join(root, 'qa-artifacts', new Date().toISOString().replace(/[:.]/g, '-'))
fs.mkdirSync(artifactRoot, { recursive: true })
const consoleEvents = []; const exceptions = []; let app
const namespace = 'biterstore:taro:v1'
const write = (name, value) => fs.writeFileSync(path.join(artifactRoot, name), typeof value === 'string' ? value : JSON.stringify(value, null, 2))
async function required(page, selector) { const element = await page.$(selector); if (!element) throw new Error(`缺少稳定元素 ${selector} @ ${page.path}`); return element }
async function shot(name) { await app.screenshot({ path: path.join(artifactRoot, `${name}.png`) }) }
async function stored(key) { const result = await app.callWxMethod('getStorage', { key: `${namespace}:${key}` }); return result?.data }
async function scenario(name, run) { try { await app.callWxMethod('clearStorage'); consoleEvents.length = 0; exceptions.length = 0; await run(); const consoleErrors = consoleEvents.filter((event) => event?.type === 'error'); if (exceptions.length || consoleErrors.length) throw new Error(`检测到 ${exceptions.length} 个异常和 ${consoleErrors.length} 个 console error`); await shot(`${name}-passed`); return { name, ok: true } } catch (error) { const page = await app.currentPage().catch(() => null); await shot(`${name}-failed`).catch(() => undefined); write(`${name}-failure.json`, { route: page?.path, error: error.stack || error.message, consoleEvents, exceptions, structure: page ? await page.wxml().catch(() => '') : '' }); return { name, ok: false, error: error.message } } }
try {
  assertLocalPaths(); app = mode === 'connect' ? await automator.connect({ wsEndpoint }) : await automator.launch({ cliPath, projectPath, port: automationPort, timeout: 60000 })
  app.on('console', (event) => consoleEvents.push(event)); app.on('exception', (event) => exceptions.push(event))
  const results = []
  results.push(await scenario('onboarding-home', async () => { await app.reLaunch('/pages/welcome/index'); let page = await app.currentPage(); await page.waitFor(150); const close = await page.$('#e2e-modal-close'); if (close) await close.tap(); await (await required(page, '#e2e-welcome-start')).tap(); for (let i = 0; i < 3; i += 1) { page = await app.currentPage(); await (await required(page, '#e2e-onboarding-next')).tap() } page = await app.currentPage(); if (page.path !== 'pages/home/index') throw new Error(`首页路由错误: ${page.path}`); await required(page, '#e2e-home-search-entry'); if (!await stored('onboarding')) throw new Error('引导完成状态未持久化') }))
  results.push(await scenario('search-detail-favorite-contact', async () => { await app.switchTab('/pages/search/index'); let page = await app.currentPage(); await (await required(page, '#e2e-search-input')).input('高等数学'); await page.waitFor(300); await (await required(page, '#e2e-listing-math-7')).tap(); page = await app.currentPage(); await (await required(page, '#e2e-detail-favorite')).tap(); if (!(await stored('favorites'))?.includes('math-7')) throw new Error('收藏未写入 Repository 存储'); await (await required(page, '#e2e-detail-contact')).tap(); page = await app.currentPage(); if (page.path !== 'pages/chat/index') throw new Error(`联系卖家未进入聊天: ${page.path}`) }))
  results.push(await scenario('publish-fixture-draft-success', async () => { await app.switchTab('/pages/publish/index'); let page = await app.currentPage(); await (await required(page, '#e2e-publish-media')).tap(); await (await required(page, '#e2e-publish-title')).input('自动化测试教材'); await (await required(page, '#e2e-publish-price')).input('16'); await (await required(page, '#e2e-publish-tobby-ai')).tap(); await (await required(page, '#e2e-publish-save')).tap(); if ((await stored('draft'))?.title !== '自动化测试教材') throw new Error('草稿未持久化'); await (await required(page, '#e2e-publish-submit')).tap(); page = await app.currentPage(); await required(page, '#e2e-state-success'); if (!(await stored('listings'))?.some((item) => item.title === '自动化测试教材')) throw new Error('发布结果未写入 Repository 存储') }))
  results.push(await scenario('messages-notification-text-image', async () => { await app.switchTab('/pages/messages/index'); let page = await app.currentPage(); await (await required(page, '#e2e-notification-n1')).tap(); page = await app.currentPage(); await required(page, '#e2e-notification-detail-comment'); await app.navigateBack(); page = await app.currentPage(); await (await required(page, '#e2e-thread-thread-lin')).tap(); page = await app.currentPage(); await (await required(page, '#e2e-message-input')).input('你好，还在吗？'); await (await required(page, '#e2e-message-send')).tap(); await (await required(page, '#e2e-message-image')).tap(); const thread = (await stored('threads'))?.find((item) => item.id === 'thread-lin'); if (!thread?.messages.some((item) => item.text === '你好，还在吗？') || !thread.messages.some((item) => item.kind === 'image')) throw new Error('文字或 fixture 图片消息未持久化') }))
  results.push(await scenario('favorites-profile-replay-reset', async () => { await app.switchTab('/pages/search/index'); let page = await app.currentPage(); await page.waitFor(200); await (await required(page, '#e2e-listing-math-7')).tap(); page = await app.currentPage(); await (await required(page, '#e2e-detail-favorite')).tap(); await app.navigateTo('/pages/favorites/index'); page = await app.currentPage(); await required(page, '#e2e-listing-math-7'); await app.switchTab('/pages/profile/index'); page = await app.currentPage(); await required(page, '#e2e-profile-reset'); await app.navigateTo('/pages/my-listings/index'); page = await app.currentPage(); await required(page, '#e2e-my-listings-empty'); await app.reLaunch('/pages/onboarding/index'); page = await app.currentPage(); await required(page, '#e2e-onboarding-next') }))
  results.push(await scenario('all-states', async () => { for (const state of ['loading', 'searching', 'empty', 'no-results', 'network', 'maintenance', 'unavailable', 'success', 'not-found']) { await app.reLaunch(`/pages/states/index?type=${state}`); const page = await app.currentPage(); await required(page, `#e2e-state-${state}`) } }))
  write('result.json', { mode, results }); const ok = results.every((x) => x.ok); console.log(JSON.stringify({ ok, artifactRoot, results }, null, 2)); if (!ok) process.exitCode = 1
} catch (error) { write('launch-failure.json', { error: error.stack || error.message }); console.error(JSON.stringify({ ok: false, artifactRoot, error: error.message }, null, 2)); process.exitCode = 1 } finally { if (app) { if (mode === 'launch') await app.close().catch(() => undefined); else await app.disconnect().catch(() => undefined) } }
