import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('production gateway', () => {
  it('preserves private media cache headers through the legacy media alias', () => {
    const nginx = readFileSync(resolve(process.cwd(), '../deploy/nginx.conf'), 'utf8')
    const mediaLocation = nginx.split('location /media/ {')[1].split('\n  }')[0]
    expect(mediaLocation).toContain('rewrite ^/media/(.*)$ /api/v1/media/$1 break;')
    expect(mediaLocation).not.toMatch(/proxy_hide_header\s+Cache-Control/)
    expect(mediaLocation).not.toMatch(/add_header\s+Cache-Control/)
  })

  it('canonicalizes dynamic H5 links and redirects unknown pages to the in-app 404', () => {
    const h5Nginx = readFileSync(resolve(process.cwd(), '../miniProgram/nginx.h5.conf'), 'utf8')
    const h5Dockerfile = readFileSync(resolve(process.cwd(), '../miniProgram/Dockerfile.h5'), 'utf8')

    expect(h5Dockerfile).toContain('COPY miniProgram/nginx.h5.conf /etc/nginx/conf.d/default.conf')
    expect(h5Nginx).toContain('absolute_redirect off;')
    expect(h5Nginx).toContain('return 302 /books?id=$1;')
    expect(h5Nginx).toContain('return 302 /chat?id=$1;')
    expect(h5Nginx).toContain('return 302 /notifications?type=$1;')
    expect(h5Nginx).toContain('return 302 /states?type=404;')
    expect(h5Nginx).toContain('location = /sw.js')
  })

  it('redirects HTTP entry points to HTTPS before Secure cookie authentication', () => {
    const nginx = readFileSync(resolve(process.cwd(), '../deploy/nginx.conf'), 'utf8')

    expect(nginx).toContain('map $http_cf_visitor $biterstore_forwarded_proto {')
    expect(nginx).toContain('map $http_x_forwarded_proto $biterstore_edge_proto {')
    expect(nginx).toContain("'{\"scheme\":\"https\"}' https;")
    expect(nginx).toContain('map $biterstore_forwarded_proto $biterstore_redirect_https {')
    expect(nginx).toContain('https 0;')
    expect(nginx).toContain('if ($biterstore_redirect_https) {')
    expect(nginx).toContain('return 308 https://store.young581.com$request_uri;')
    expect(nginx.indexOf('return 308 https://store.young581.com$request_uri;')).toBeLessThan(nginx.indexOf('location /api/'))
    expect(nginx.indexOf('return 308 https://store.young581.com$request_uri;')).toBeLessThan(nginx.indexOf('location / {'))
    expect(nginx).toContain('map $biterstore_forwarded_proto $biterstore_redirect_https {')
    expect(nginx).toContain('map $biterstore_forwarded_proto $biterstore_hsts {')
    expect(nginx).toContain('add_header Strict-Transport-Security $biterstore_hsts always;')
    expect(nginx).toContain('add_header X-Content-Type-Options nosniff always;')
    expect(nginx).toContain('add_header X-Frame-Options DENY always;')
    expect(nginx).toContain('add_header Permissions-Policy')
    expect(nginx).toContain("location /media/")
    expect(nginx).toContain('proxy_set_header X-Forwarded-Proto $biterstore_forwarded_proto;')
    expect(nginx).toContain("location /api/")
    expect(nginx).toContain('location = /admin {')
    expect(nginx).toContain('return 308 https://store.young581.com/admin/;')
    expect(nginx.indexOf('location = /admin {')).toBeLessThan(nginx.indexOf('location /admin/ {'))
    expect(nginx).toContain("location / {")
    const adminDockerfile = readFileSync(resolve(process.cwd(), '../admin/Dockerfile'), 'utf8')
    expect(adminDockerfile).toContain('absolute_redirect off;')
    expect(adminDockerfile).toContain('location = /admin { return 308 /admin/; }')
  })

  it('only exposes the BIT-Login challenge routes and rate-limits authentication', () => {
    const nginx = readFileSync(resolve(process.cwd(), '../deploy/nginx.conf'), 'utf8')
    expect(nginx).toContain('map "$request_method:$uri" $biterstore_bit_login_allowed')
    expect(nginx).toContain('"POST:/bit-login/api/auth/start" 1;')
    expect(nginx).toContain('registration-token$ 1;')
    expect(nginx).toContain('if ($biterstore_bit_login_allowed = 0) { return 404; }')
    expect(nginx).toContain('limit_req zone=biterstore_bit_login_start burst=5 nodelay;')
    expect(nginx).toContain('rewrite ^/bit-login(/.*)$ $1 break;')
    expect(nginx).not.toContain('proxy_pass http://bit-login:16384/;')
  })

  it('uses query-free gateway access logs and a global API safety cap', () => {
    const nginx = readFileSync(resolve(process.cwd(), '../deploy/nginx.conf'), 'utf8')
    expect(nginx).toContain('log_format biterstore_sanitized')
    expect(nginx).toContain('"$request_method $uri $server_protocol"')
    expect(nginx).not.toContain('$http_referer')
    expect(nginx).toContain('limit_req zone=biterstore_api_global burst=300 nodelay;')
    expect(nginx).toContain('limit_conn biterstore_api_connections 300;')
    expect(nginx).toContain('zone=biterstore_catalog_list:10m rate=60r/m;')
    expect(nginx).toContain('zone=biterstore_catalog_search:10m rate=30r/m;')
    expect(nginx).toContain('zone=biterstore_catalog_detail:10m rate=120r/m;')
    expect(nginx).toContain('zone=biterstore_book_lookup:10m rate=30r/m;')
    expect(nginx).toContain('zone=biterstore_book_lookup_global:10m rate=2r/s;')
    expect(nginx).toContain('limit_req zone=biterstore_book_lookup burst=10 nodelay;')
    expect(nginx).toContain('zone=biterstore_media:10m rate=180r/m;')
    expect(nginx).toContain('limit_req zone=biterstore_media burst=60 nodelay;')
    expect(nginx).toContain('zone=biterstore_auth_exchange:10m rate=30r/m;')
    expect(nginx).toContain('zone=biterstore_auth_exchange_global:10m rate=10r/s;')
    expect(nginx).toContain('zone=biterstore_auth_poll:10m rate=120r/m;')
    expect(nginx).toContain('proxy_set_header X-Forwarded-For $biterstore_client_address;')
  })
})

describe('production service isolation and recovery', () => {
  it('protects Redis, separates networks and gates the gateway on readiness', () => {
    const compose = readFileSync(resolve(process.cwd(), '../deploy/config.yaml'), 'utf8')
    expect(compose).toContain('user default off')
    expect(compose).toContain('user biterstore on')
    expect(compose).toContain('user: redis')
    expect(compose).toContain('cap_drop: ["ALL"]')
    expect(compose).toContain('REDIS_USERNAME: biterstore')
    expect(compose).toContain('networks: [data]')
    expect(compose).toMatch(/data:\r?\n\s+internal: true/)
    expect(compose).toContain('READINESS_TIMEOUT_MS: "5000"')
    expect(compose).toContain('timeout: 8s')
    expect(compose).toContain("health/ready")
    expect(compose).toContain('api: { condition: service_healthy }')
  })

  it('writes only integrity-checked encrypted database archives', () => {
    const compose = readFileSync(resolve(process.cwd(), '../deploy/config.yaml'), 'utf8')
    const backup = readFileSync(resolve(process.cwd(), '../deploy/backup/backup.sh'), 'utf8')
    const backupHealth = readFileSync(resolve(process.cwd(), '../deploy/backup/backup-health.sh'), 'utf8')
    const restoreDrill = readFileSync(resolve(process.cwd(), '../deploy/backup/restore-drill.sh'), 'utf8')
    const backupDockerfile = readFileSync(resolve(process.cwd(), '../deploy/backup/Dockerfile'), 'utf8')
    const serverDockerfile = readFileSync(resolve(process.cwd(), 'Dockerfile'), 'utf8')
    const gitAttributes = readFileSync(resolve(process.cwd(), '../.gitattributes'), 'utf8')
    const npmGuide = readFileSync(resolve(process.cwd(), '../deploy/npm/README.md'), 'utf8')
    expect(compose).toContain('BACKUP_ENCRYPTION_PASSPHRASE_FILE: /run/secrets/backup_passphrase')
    expect(compose).toContain('user: "${BACKUP_RUN_UID:-1000}:${BACKUP_RUN_GID:-1000}"')
    expect(compose).toContain('test: ["CMD", "/usr/local/bin/backup-health.sh"]')
    expect(backup).toContain('mktemp /tmp/biterstore-backup-XXXXXX')
    expect(backup).not.toContain('mktemp /tmp/biterstore-backup-XXXXXX.dump')
    expect(backup).toContain('pg_restore --list "$plain_file"')
    expect(backup).toContain('gpg --batch --yes --no-symkey-cache')
    expect(backup).toContain('--cipher-algo AES256')
    expect(backup).toContain('mktemp /tmp/biterstore-backup-verify.XXXXXX')
    expect(backup).toContain('--output "$verification_file" --decrypt "$temporary_file"')
    expect(backup).toContain('cmp -s "$plain_file" "$verification_file"')
    expect(backup).toContain('pg_restore --list "$verification_file"')
    expect(backup).not.toContain('--decrypt "$temporary_file" | pg_restore')
    expect(backup).toContain('mv "$temporary_file" "$final_file"')
    expect(backup).toContain('touch /tmp/biterstore-backup-ready')
    expect(backup).toContain('rm -f /tmp/biterstore-backup-ready')
    expect(backupHealth).toContain('test -f /tmp/biterstore-backup-ready')
    expect(restoreDrill).toContain('mktemp /tmp/biterstore-restore.dump.XXXXXX')
    expect(restoreDrill).toContain('gpg --batch --yes --quiet')
    expect(restoreDrill).not.toContain('mktemp /tmp/biterstore-restore-XXXXXX.dump')
    expect(backupDockerfile).toContain("sed -i 's/\\r$//' /usr/local/bin/*.sh")
    expect(gitAttributes).toContain('*.sh text eol=lf')
    expect(serverDockerfile).toContain('chmod 0444 /app/package*.json')
    expect(serverDockerfile).toContain('chmod -R a+rX /app/prisma')
    expect(serverDockerfile).toContain('chown -R node:node /app/uploads')
    expect(serverDockerfile).not.toContain('chown -R node:node /app\n')
    expect(npmGuide).not.toContain('vip.hb.2.frp.one')
  })
})
